# release workflow

name: Release
on:
  release:

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.16'
    - name: Install splunk toolkit
      run: |
        curl https://download.splunk.com/misc/packaging-toolkit/splunk-packaging-toolkit-1.0.1.tar.gz -o /tmp/spl.tar.gz
        pip install /tmp/spl.tar.gz
    - name: Make package
      run: |
        rm -rf .git .github .gitignore
        slim package .
        cp crowdsec-splunk-app-*.tar.gz  ./crowdsec-splunk-app.tar.gz
    
    - name: Upload to SplunkBase
      run: |
        curl -u "${{ secrets.SPLUNKBASE_USERNAME }}:${{ secrets.SPLUNKBASE_PASSWORD }}"   --request POST \
        "https://splunkbase.splunk.com/api/v1/app/6800/new_release/" \
        -F "files[]=@crowdsec-splunk-app.tar.gz" \
        -F "filename=crowdsec-splunk-app.tar.gz" \
        -F "cim_versions=5.x" \
        -F "splunk_versions=9.0" \
        -F "visibility=true" 